name: ScriptRunner

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "*/15 * * * *"  
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    environment: INS
    strategy:
      matrix:
        node-version: ["20.x"]
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        git clone https://${{ secrets.REPO }}@git.code.tencent.com/pandazxs/crawl_insurance.git
        cd crawl_insurance
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: crawl
      env:
        REDISURL: ${{ secrets.REDISURL }}
        REDISPASSWORD: ${{ secrets.REDISPASSWORD }}
        PGURL: ${{ secrets.PGURL }}
        FILE_PATH: ${{ secrets.FILE_PATH }}
        PROXY_IP_POOL_SERVER: ${{ secrets.PROXY_IP_POOL_SERVER }}
      run: |
        python -u src/cli.py
